git-related bugfix

diff --git a/fenix/config/functions/build b/fenix/config/functions/build
--- a/fenix/config/functions/build
+++ b/fenix/config/functions/build
@@ -26,39 +26,39 @@ build_uboot() {
 	fi
 
 	cd ${ROOT}
-	if [ ! -d "$UBOOT_VENDOR_DIR"/.git ]; then
-		info_msg "U-boot repository does not exist, clone u-boot repository('$UBOOT_GIT_BRANCH') from '$UBOOT_SOURCE_URL'..."
-		## Clone u-boot from Khadas GitHub
-		git clone $GIT_CLONE_OPTIONS $UBOOT_SOURCE_URL -b $UBOOT_GIT_BRANCH "$UBOOT_VENDOR_DIR"
-		[ $? != 0 ] && error_msg "Failed to clone 'u-boot'" && return -1
-	fi
+#	if [ ! -d "$UBOOT_VENDOR_DIR"/.git ]; then
+#		info_msg "U-boot repository does not exist, clone u-boot repository('$UBOOT_GIT_BRANCH') from '$UBOOT_SOURCE_URL'..."
+#		## Clone u-boot from Khadas GitHub
+#		git clone $GIT_CLONE_OPTIONS $UBOOT_SOURCE_URL -b $UBOOT_GIT_BRANCH "$UBOOT_VENDOR_DIR"
+#		[ $? != 0 ] && error_msg "Failed to clone 'u-boot'" && return -1
+#	fi
 
 	cd "$UBOOT_VENDOR_DIR"
 	touch .scmversion
 
-	if ! git branch | grep "^* $UBOOT_GIT_BRANCH$" > /dev/null; then
-		if ! git branch | grep "^  $UBOOT_GIT_BRANCH$" > /dev/null; then
-			# New branch? Try to fetch it.
-			info_msg "Fetching '$UBOOT_GIT_BRANCH' from '$UBOOT_SOURCE_URL'..."
-			git fetch origin $UBOOT_GIT_BRANCH:$UBOOT_GIT_BRANCH
-		fi
-
+#	if ! git branch | grep "^* $UBOOT_GIT_BRANCH$" > /dev/null; then
+#		if ! git branch | grep "^  $UBOOT_GIT_BRANCH$" > /dev/null; then
+#			# New branch? Try to fetch it.
+#			info_msg "Fetching '$UBOOT_GIT_BRANCH' from '$UBOOT_SOURCE_URL'..."
+#			git fetch origin $UBOOT_GIT_BRANCH:$UBOOT_GIT_BRANCH
+#		fi
+#
 		info_msg "U-boot: Switch to branch '$UBOOT_GIT_BRANCH'"
 		make distclean
-		# Check modifications
-		check_modifications || {
-			error_msg "U-boot: can't checkout to branch '$UBOOT_GIT_BRANCH', please commit your modifications and try again!"
-			return -1
-		}
-
-		git checkout $UBOOT_GIT_BRANCH
-		[ $? != 0 ] && error_msg "U-boot: Switch to branch '$UBOOT_GIT_BRANCH' failed." && return -1
-	else
+#		# Check modifications
+#		check_modifications || {
+#			error_msg "U-boot: can't checkout to branch '$UBOOT_GIT_BRANCH', please commit your modifications and try again!"
+#			return -1
+#		}
+#
+#		git checkout $UBOOT_GIT_BRANCH
+#		[ $? != 0 ] && error_msg "U-boot: Switch to branch '$UBOOT_GIT_BRANCH' failed." && return -1
+#	else
 		info_msg "U-boot: Already on branch '$UBOOT_GIT_BRANCH'"
-	fi
+#	fi
 
 	# Update u-boot
-	update_git_repo "$PWD" "$UBOOT_GIT_BRANCH"
+#	update_git_repo "$PWD" "$UBOOT_GIT_BRANCH"
 
 	info_msg "Build u-boot..."
 	export PATH=$UBOOT_COMPILER_PATH:$PATH
@@ -97,22 +97,22 @@ build_linux() {
 	fi
 
 	cd ${ROOT}
-	if [ ! -d "$LINUX_VENDOR_DIR"/.git ]; then
-		info_msg "Linux repository does not exist, clone linux repository('$LINUX_GIT_BRANCH') from '$LINUX_SOURCE_URL'..."
-		## Clone linux from Khadas GitHub
-		git clone $GIT_CLONE_OPTIONS $LINUX_SOURCE_URL -b $LINUX_GIT_BRANCH "$LINUX_VENDOR_DIR"
-		[ $? != 0 ] && error_msg "Failed to clone 'linux'" && return -1
-	fi
+#	if [ ! -d "$LINUX_VENDOR_DIR"/.git ]; then
+#		info_msg "Linux repository does not exist, clone linux repository('$LINUX_GIT_BRANCH') from '$LINUX_SOURCE_URL'..."
+#		## Clone linux from Khadas GitHub
+#		git clone $GIT_CLONE_OPTIONS $LINUX_SOURCE_URL -b $LINUX_GIT_BRANCH "$LINUX_VENDOR_DIR"
+#		[ $? != 0 ] && error_msg "Failed to clone 'linux'" && return -1
+#	fi
 
 	cd "$LINUX_VENDOR_DIR"
 	touch .scmversion
 
-	if ! git branch | grep "^* $LINUX_GIT_BRANCH$" > /dev/null; then
-		if ! git branch | grep "^  $LINUX_GIT_BRANCH$" > /dev/null; then
-			# New branch? Try to fetch it.
-			info_msg "Fetching '$LINUX_GIT_BRANCH' from '$LINUX_SOURCE_URL'..."
-			git fetch origin $LINUX_GIT_BRANCH:$LINUX_GIT_BRANCH
-		fi
+#	if ! git branch | grep "^* $LINUX_GIT_BRANCH$" > /dev/null; then
+#		if ! git branch | grep "^  $LINUX_GIT_BRANCH$" > /dev/null; then
+#			# New branch? Try to fetch it.
+#			info_msg "Fetching '$LINUX_GIT_BRANCH' from '$LINUX_SOURCE_URL'..."
+#			git fetch origin $LINUX_GIT_BRANCH:$LINUX_GIT_BRANCH
+#		fi
 
 		info_msg "Linux: Switch to branch '$LINUX_GIT_BRANCH'"
 		make ARCH=arm64 distclean
@@ -122,21 +122,21 @@ build_linux() {
 			rm drivers/gpu/arm/mali400/mali/__malidrv_build_info.c
 		fi
 
-		# Check modifications
-		check_modifications || {
-			error_msg "Linux: can't checkout to branch '$LINUX_GIT_BRANCH', please commit your modifications and try again!"
-
-			return -1
-		}
-
-		git checkout $LINUX_GIT_BRANCH
-		[ $? != 0 ] && error_msg "Linux: Switch to branch '$LINUX_GIT_BRANCH' failed." && return -1
-	else
+#		# Check modifications
+#		check_modifications || {
+#			error_msg "Linux: can't checkout to branch '$LINUX_GIT_BRANCH', please commit your modifications and try again!"
+#
+#			return -1
+#		}
+#
+#		git checkout $LINUX_GIT_BRANCH
+#		[ $? != 0 ] && error_msg "Linux: Switch to branch '$LINUX_GIT_BRANCH' failed." && return -1
+#	else
 		info_msg "Linux: Already on branch '$LINUX_GIT_BRANCH'"
-	fi
+#	fi
 
 	# Update linux
-	update_git_repo "$PWD" "$LINUX_GIT_BRANCH"
+#	update_git_repo "$PWD" "$LINUX_GIT_BRANCH"
 
 	# no need build just prepare
 	[ ! "$BUILD_LINUX_NOOP" ] || return 0
